import { useMDXComponents as getDocsMDXComponents } from "nextra-theme-docs";
import { ComponentPreview } from "./components/ComponentPreview";
import { BadgePropsDoc, ButtonPropsDoc } from "./components/PropsTables";
import {
  IntroDemo,
  ButtonDemo,
  ButtonVariantDemo,
  ButtonSizeDemo,
  ButtonIntentDemo,
  ButtonRoundedDemo,
  ButtonDisabledDemo,
  BadgeDemo,
  BadgeVariantDemo,
  BadgeIntentDemo,
  BadgeSizeDemo,
  BadgeDotDemo,
  CheckboxDemo,
  CheckboxIntentDemo,
  CheckboxSizeDemo,
  DropdownDemo,
  DropdownSizeDemo,
  SwitchDemo,
  SwitchIntentDemo,
  SwitchSizeDemo,
  TabDemo,
  TabVerticalDemo,
  TextDemo,
  TextSizeDemo,
  TextWeightDemo,
  TextIntentDemo,
  TextFieldDemo,
  TextFieldVariantDemo,
  TextFieldStatusDemo,
  TextFieldMultilineDemo,
} from "./components/Demos";

const docsComponents = getDocsMDXComponents();

export function useMDXComponents(components?: Record<string, unknown>) {
  return {
    ...docsComponents,
    ComponentPreview,
    BadgePropsDoc,
    ButtonPropsDoc,
    IntroDemo,
    ButtonDemo,
    ButtonVariantDemo,
    ButtonSizeDemo,
    ButtonIntentDemo,
    ButtonRoundedDemo,
    ButtonDisabledDemo,
    BadgeDemo,
    BadgeVariantDemo,
    BadgeIntentDemo,
    BadgeSizeDemo,
    BadgeDotDemo,
    CheckboxDemo,
    CheckboxIntentDemo,
    CheckboxSizeDemo,
    DropdownDemo,
    DropdownSizeDemo,
    SwitchDemo,
    SwitchIntentDemo,
    SwitchSizeDemo,
    TabDemo,
    TabVerticalDemo,
    TextDemo,
    TextSizeDemo,
    TextWeightDemo,
    TextIntentDemo,
    TextFieldDemo,
    TextFieldVariantDemo,
    TextFieldStatusDemo,
    TextFieldMultilineDemo,
    ...components,
  };
}
