import { useMDXComponents as getDocsMDXComponents } from "nextra-theme-docs";
import { ComponentPreview, DocTable, PropsDoc } from "./components/content";
import {
  ColorPalette,
  ColorTokenTable,
  TypographyScale,
  FontWeightPreview,
  FontFamilyPreview,
  RadiusScale,
  ShadowScale,
  SpacingScale,
} from "./components/foundation";
import {
  IntroDemo,
  ButtonDemo,
  ButtonVariantDemo,
  ButtonSizeDemo,
  ButtonIntentDemo,
  ButtonRoundedDemo,
  ButtonDisabledDemo,
  BadgeDemo,
  BadgeVariantDemo,
  BadgeIntentDemo,
  BadgeSizeDemo,
  BadgeDotDemo,
  CheckboxDemo,
  CheckboxIntentDemo,
  CheckboxSizeDemo,
  DropdownDemo,
  DropdownSizeDemo,
  SwitchDemo,
  SwitchIntentDemo,
  SwitchSizeDemo,
  TabDemo,
  TabVerticalDemo,
  TextDemo,
  TextSizeDemo,
  TextWeightDemo,
  TextIntentDemo,
  TextFieldDemo,
  TextFieldVariantDemo,
  TextFieldStatusDemo,
  TextFieldMultilineDemo,
} from "./components/demos";

const docsComponents = getDocsMDXComponents();

export function useMDXComponents(components?: Record<string, unknown>) {
  return {
    ...docsComponents,
    ComponentPreview,
    DocTable,
    PropsDoc,
    ColorPalette,
    ColorTokenTable,
    TypographyScale,
    FontWeightPreview,
    FontFamilyPreview,
    RadiusScale,
    ShadowScale,
    SpacingScale,
    IntroDemo,
    ButtonDemo,
    ButtonVariantDemo,
    ButtonSizeDemo,
    ButtonIntentDemo,
    ButtonRoundedDemo,
    ButtonDisabledDemo,
    BadgeDemo,
    BadgeVariantDemo,
    BadgeIntentDemo,
    BadgeSizeDemo,
    BadgeDotDemo,
    CheckboxDemo,
    CheckboxIntentDemo,
    CheckboxSizeDemo,
    DropdownDemo,
    DropdownSizeDemo,
    SwitchDemo,
    SwitchIntentDemo,
    SwitchSizeDemo,
    TabDemo,
    TabVerticalDemo,
    TextDemo,
    TextSizeDemo,
    TextWeightDemo,
    TextIntentDemo,
    TextFieldDemo,
    TextFieldVariantDemo,
    TextFieldStatusDemo,
    TextFieldMultilineDemo,
    ...components,
  };
}
